# Enable 256-color support and true color
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",alacritty:Tc"

# Enable mouse support (works for panes, windows, and scrolling)
set -g mouse on

# Set the status bar at the bottom
set -g status-position bottom

# Set the status bar colors (optional)
set -g status-bg black
set -g status-fg white

# Show current window, session, and time in status bar
# set -g status-right "#H | %Y-%m-%d %H:%M"

# Split panes more easily using | and -
bind | split-window -h
bind - split-window -v

setw -g automatic-rename on
setw -g automatic-rename-format "#{b:pane_current_command}"

set -g history-limit 10000

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

